# Generated by Django 2.1.2 on 2019-11-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gam_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='profesión',
            new_name='ocupación',
        ),
    ]
